### ISSUE TITLE
H4 - Should this be centered or not?

### ISSUE THREAD

**Issue by LauraMJ** [daradermody/laura-portfolio#9]
Discuss what to do with the styling of H3 in general.
Centered looks good in some cases, but not in others

**Comment by daradermody** [comment]
Move to 1.1 rem and remove centre (test the second)

**Comment by daradermody** [comment]
Changed and pushed to production server. Example:
![image](https://user-images.githubusercontent.com/7104356/47744321-f63a4400-dc78-11e8-8674-725453715b83.png)

@LauraMJ, let me know if this is ok.

**Comment by LauraMJ** [comment]
Looks good, make it so!
